plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.androidnode'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.androidnode"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86_64"
        }

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs 'libnode/bin/'
        }
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}
